apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: logging
data:
  fluent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /fluentd/log/positions.log
      tag kube.*
      read_from_head true
      <parse>
        @type cri
      </parse>
    </source>

    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    <match **>
      @type stdout
    </match>