apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd
  namespace: logging
  labels:
    app: fluentd
spec:
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      serviceAccountName: fluentd
      tolerations:
        - key: "node-role.kubernetes.io/control-plane"
          operator: "Exists"
          effect: "NoSchedule"
        - key: "node-role.kubernetes.io/master"
          operator: "Exists"
          effect: "NoSchedule"
      containers:
        - name: fluentd
          # Imagen con plugins (incluye kubernetes_metadata)
          image: ghcr.io/fluent/fluentd-kubernetes-daemonset:v1.16.3-debian
          env:
            - name: FLUENTD_CONF
              value: fluent.conf
            - name: FLUENT_UID
              value: "0"
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              memory: 300Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: dockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: containerd
              mountPath: /var/lib/containerd
              readOnly: true
            - name: config
              mountPath: /fluentd/etc
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        - name: dockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: containerd
          hostPath:
            path: /var/lib/containerd
        - name: config
          configMap:
            name: fluentd-config
