apiVersion: v1
kind: Pod
metadata:
  name: log-generator
  namespace: app
  labels:
    app: log-generator
spec:
  containers:
  - name: busybox
    image: busybox:1.36
    command: ["/bin/sh", "-c"]
    args:
      - |
        while true; do
          echo "$(date) - Hola KCD Bogotá desde Fluentd!";
          sleep 5;
        done
